spring:
  profiles:
    active: dev

packaged.jdbc.driver.classes: postgresql|org.postgresql.Driver,mysql|com.mysql.cj.jdbc.Driver,sqlserver|com.microsoft.sqlserver.jdbc.SQLServerDriver

---

spring:
  profiles: dev

server:
  port: 8443
  ssl:
    enabled: true
    key-alias: tomcat
    key-store: classpath:devkeystore.p12
    key-store-password: devonly
    key-store-type: PKCS12

---

spring:
  profiles: prod

---