spring:
  profiles:
    active: dev

packaged.jdbc.driver.classes: postgresql,mysql,sqlserver

preview.limit: 100
report.limit: 5000

---

spring:
  profiles: dev

server:
  port: 8443
  ssl:
    enabled: true
    key-alias: tomcat
    key-store: classpath:devkeystore.p12
    key-store-password: devonly
    key-store-type: PKCS12


sample:
  user: appuser
  password: localpass
  endpoint: jdbc:postgresql://localhost/sales_all
  vendor: postgresql

---

spring:
  profiles: prod

---